project:
  type: website
  output-dir: _site

website:
  title: "web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: QTP_Wile copy.qmd
        text: Quantitative Trading

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

