project:
  type: website
  output-dir: _site

website:
  title: "Matthew Wile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: QTP_Wile copy.qmd
        text: Quantitative Trading
      - href: volatility trading copy.qmd
        text: Volatility Trading

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

